export const MS2AdditionalOptions = {
    "headgear":[
        { name: 'STR', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'DEX', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'INT', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'LUK', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '명중', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '마법 공격력', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.029412 , optionGroup : "YellowGroup"},
        { name: 'HP', probability: 0.052941 },
        { name: '회피', probability: 0.052941 },
        { name: '크리티컬 회피', probability: 0.052941 },
        { name: '물리 저항력', probability: 0.052941 },
        { name: '마법 저항력', probability: 0.052941 },
        { name: '처치 시 HP회복', probability: 0.052941 },
        { name: '냉기 대미지 감소', probability: 0.052941 },
        { name: '화염 대미지 감소', probability: 0.052941},
        { name: '암흑 대미지 감소', probability: 0.052941},
        { name: '신성 대미지 감소', probability: 0.052941},
        { name: '독 대미지 감소', probability: 0.052941},
        { name: '전격 대미지 감소', probability: 0.052941 },
        { name: '행동 불가 시간 감소', probability: 0.052941 },
        { name: '근접 대미지 감소', probability: 0.052941 },
        { name: '원거리 대미지 감소', probability: 0.052941 },
    ],
    "top":[
        { name: 'STR', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'DEX', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'INT', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'LUK', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '명중', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '마법 공격력', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.029412 , optionGroup : "YellowGroup"},
        { name: 'HP', probability: 0.052941 },
        { name: '회피', probability: 0.052941 },
        { name: '크리티컬 회피', probability: 0.052941 },
        { name: '물리 저항력', probability: 0.052941 },
        { name: '마법 저항력', probability: 0.052941 },
        { name: '처치 시 HP회복', probability: 0.052941 },
        { name: '냉기 대미지 감소', probability: 0.052941 },
        { name: '화염 대미지 감소', probability: 0.052941},
        { name: '암흑 대미지 감소', probability: 0.052941},
        { name: '신성 대미지 감소', probability: 0.052941},
        { name: '독 대미지 감소', probability: 0.052941},
        { name: '전격 대미지 감소', probability: 0.052941 },
        { name: '행동 불가 시간 감소', probability: 0.052941 },
        { name: '근접 대미지 감소', probability: 0.052941 },
        { name: '원거리 대미지 감소', probability: 0.052941 },
    ],
    "bottom":[
        { name: 'STR', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'DEX', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'INT', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: 'LUK', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '명중', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '마법 공격력', probability: 0.029412, optionGroup : "YellowGroup" },
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.029412 , optionGroup : "YellowGroup"},
        { name: 'HP', probability: 0.052941 },
        { name: '회피', probability: 0.052941 },
        { name: '크리티컬 회피', probability: 0.052941 },
        { name: '물리 저항력', probability: 0.052941 },
        { name: '마법 저항력', probability: 0.052941 },
        { name: '처치 시 HP회복', probability: 0.052941 },
        { name: '냉기 대미지 감소', probability: 0.052941 },
        { name: '화염 대미지 감소', probability: 0.052941},
        { name: '암흑 대미지 감소', probability: 0.052941},
        { name: '신성 대미지 감소', probability: 0.052941},
        { name: '독 대미지 감소', probability: 0.052941},
        { name: '전격 대미지 감소', probability: 0.052941 },
        { name: '행동 불가 시간 감소', probability: 0.052941 },
        { name: '근접 대미지 감소', probability: 0.052941 },
        { name: '원거리 대미지 감소', probability: 0.052941 },
    ],
    "shoes":[
        { name: 'STR', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: 'DEX', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: 'INT', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: 'LUK', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: '명중', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: '마법 공격력', probability: 0.037313, optionGroup : "YellowGroup" },
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.037313 , optionGroup : "YellowGroup"},
        { name: 'HP', probability: 0.067164 },
        { name: '이동속도', probability: 0.067164 },
        { name: '회피', probability: 0.067164 },
        { name: '크리티컬 회피', probability: 0.067164 },
        { name: '물리 저항력', probability: 0.067164 },
        { name: '마법 저항력', probability: 0.067164 },
        { name: '처치 시 HP회복', probability: 0.067164 },
        { name: '행동 불가 시간 감소', probability: 0.067164 },
        { name: '근접 대미지 감소', probability: 0.067164 },
        { name: '원거리 대미지 감소', probability: 0.067164 },
        { name: '넉백 저항', probability: 0.067164 },
    ],
    "gloves":[
        { name: '마법 저항력 관통', probability: 0.129032, optionGroup : "YellowGroup" },
        { name: 'HP', probability: 0.058065 },
        { name: '회피', probability: 0.058065 },
        { name: '크리티컬 회피', probability: 0.058065 },
        { name: '물리 저항력', probability: 0.058065 },
        { name: '마법 저항력', probability: 0.058065 },
        { name: '처치 시 HP회복', probability: 0.058065 },
        { name: '냉기 대미지 감소', probability: 0.058065 },
        { name: '화염 대미지 감소', probability: 0.058065},
        { name: '암흑 대미지 감소', probability: 0.058065},
        { name: '신성 대미지 감소', probability: 0.058065},
        { name: '독 대미지 감소', probability: 0.058065},
        { name: '전격 대미지 감소', probability: 0.058065 },
        { name: '행동 불가 시간 감소', probability: 0.058065 },
        { name: '근접 대미지 감소', probability: 0.058065 },
        { name: '원거리 대미지 감소', probability: 0.058065 },
    ],
    "earrings":[
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.078947 , optionGroup : "BlueGroup"},
        { name: '근접 대미지 증가', probability: 0.078947, optionGroup : "BlueGroup" },
        { name: '원거리 대미지 증가', probability: 0.078947, optionGroup : "BlueGroup" },
        { name: '냉기 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '화염 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup"},
        { name: '암흑 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '신성 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '독 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '전격 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '공격속도', probability: 0.078947 },
        { name: '명중', probability: 0.078947 },
        { name: '크리티컬 명중', probability: 0.078947 },
        { name: '크리티컬 대미지', probability: 0.078947 },
        { name: '방어력 관통', probability: 0.078947 },
        { name: '행동 불가 시간 감소', probability: 0.052632 },
    ],
    "cape":[
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.06 , optionGroup : "BlueGroup"},
        { name: '냉기 대미지 증가', probability: 0.04, optionGroup : "BlueGroup" },
        { name: '화염 대미지 증가', probability: 0.04, optionGroup : "BlueGroup"},
        { name: '암흑 대미지 증가', probability: 0.04, optionGroup : "BlueGroup" },
        { name: '신성 대미지 증가', probability: 0.04, optionGroup : "BlueGroup" },
        { name: '독 대미지 증가', probability: 0.04, optionGroup : "BlueGroup" },
        { name: '전격 대미지 증가', probability: 0.04, optionGroup : "BlueGroup" },
        { name: '상태 이상 시간 감소', probability: 0.12 },
        { name: '공격속도', probability: 0.06 },
        { name: '이동속도', probability: 0.06 },
        { name: '크리티컬 명중', probability: 0.06 },
        { name: '크리티컬 대미지', probability: 0.06 },
        { name: '방어력 관통', probability: 0.06 },
        { name: '냉기 대미지 감소', probability: 0.04 },
        { name: '화염 대미지 감소', probability: 0.04},
        { name: '암흑 대미지 감소', probability: 0.04},
        { name: '신성 대미지 감소', probability: 0.04},
        { name: '독 대미지 감소', probability: 0.04},
        { name: '전격 대미지 감소', probability: 0.04 },
        { name: '행동 불가 시간 감소', probability: 0.04 },
    ],
    "rings":[
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.068182 , optionGroup : "BlueGroup"},
        { name: '근접 대미지 증가', probability: 0.068182, optionGroup : "BlueGroup" },
        { name: '원거리 대미지 증가', probability: 0.068182, optionGroup : "BlueGroup" },
        { name: '냉기 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup" },
        { name: '화염 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup"},
        { name: '암흑 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup" },
        { name: '신성 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup" },
        { name: '독 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup" },
        { name: '전격 대미지 증가', probability: 0.045455, optionGroup : "BlueGroup" },
        { name: '넉백 저항', probability: 0.136364 },
        { name: '공격속도', probability: 0.068182 },
        { name: '명중', probability: 0.068182 },
        { name: '크리티컬 명중', probability: 0.068182 },
        { name: '크리티컬 대미지', probability: 0.068182 },
        { name: '방어력 관통', probability: 0.068182 },
        { name: '행동 불가 시간 감소', probability: 0.045455 },
    ],
    "necklace":[
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.078947 , optionGroup : "BlueGroup"},
        { name: '냉기 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '화염 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup"},
        { name: '암흑 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '신성 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '독 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '전격 대미지 증가', probability: 0.052632, optionGroup : "BlueGroup" },
        { name: '공격속도', probability: 0.078947 },
        { name: '명중', probability: 0.078947 },
        { name: '크리티컬 명중', probability: 0.078947 },
        { name: '크리티컬 대미지', probability: 0.078947 },
        { name: '방어력 관통', probability: 0.078947 },
        { name: '물리 저항력 관통', probability: 0.078947 },
        { name: '마법 저항력 관통', probability: 0.078947 },
        { name: '행동 불가 시간 감소', probability: 0.052632 },
    ],
    "belt":[
        { name: '보스 몬스터 공격 시 대미지 증가', probability: 0.0732 , optionGroup : "BlueGroup"},
        { name: '근접 대미지 증가', probability: 0.0732, optionGroup : "BlueGroup" },
        { name: '원거리 대미지 증가', probability: 0.0732, optionGroup : "BlueGroup" },
        { name: '냉기 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup" },
        { name: '화염 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup"},
        { name: '암흑 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup" },
        { name: '신성 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup" },
        { name: '독 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup" },
        { name: '전격 대미지 증가', probability: 0.0488, optionGroup : "BlueGroup" },
        { name: '넉백 저항', probability: 0.1463 },
        { name: '공격속도', probability: 0.0732 },
        { name: '크리티컬 명중', probability: 0.0732 },
        { name: '크리티컬 대미지', probability: 0.0732 },
        { name: '방어력 관통', probability: 0.0732 },
        { name: '행동 불가 시간 감소', probability: 0.0488 },
    ]
    
}

let _MS2AdditionalOptionChangeFee={
    "epic": {crystalFragments : 400},
    "legendary": {crystalFragments : 2000},
    "ascendant": {crystalFragments : 2400},
};

export const MS2AdditionalOptionChangeFee={
    ..._MS2AdditionalOptionChangeFee,
    "엑설런트":_MS2AdditionalOptionChangeFee["epic"],
    "레전더리":_MS2AdditionalOptionChangeFee["legendary"],
    "에픽":_MS2AdditionalOptionChangeFee["ascendant"],
}


const optionChangeFeeRaito_Equipment = {
    crystalFragments:[
        1,  //0회
        1.25,
        1.56,
        1.95,
        2.44,
        3.05,
        3.81,
        4.765,
        5.96,
        7.45,
        8.59,
        10.65,
        13.21,
        16.385,
        20.315  //14회(옵션 변경 15회 시도), MAX
    ],
    colorCrystals:[1],
    metacells : [

    ]
    
}

export const optionChangeFeeRatios = {
    "necklace" : {...optionChangeFeeRaito_Equipment},
    "cape" : {...optionChangeFeeRaito_Equipment},
    "rings" : {...optionChangeFeeRaito_Equipment},
    "earings" : {...optionChangeFeeRaito_Equipment},
    "belt" : {...optionChangeFeeRaito_Equipment},
}